### ISSUE TITLE
Add hacktoberfest inside the repo topics list

### ISSUE THREAD

**Issue by vr1e** [gawangnich/HacktoberFest2020#65]
To follow the latest rules for Hacktoberfest 2020 the repo needs to have the hacktoberfest topic set.

> Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

![image](https://user-images.githubusercontent.com/17619481/95757341-50d2dc00-0ca7-11eb-922c-3865c467b8bf.png)

**Comment by gawangnich** [comment]
oke , thank you for your information
